varName: cartservice
replicas:  2
imageName:  gcr.io/google-samples/microservices-demo/cartservice
imageVersion: v0.8.1
varPort: 7070
envVar:
- name: REDIS_ADDR
  value: "redis-cart:6379"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 7070
serviceType: ClusterIP