varName: checkoutservice
replicas:  2
imageName:  gcr.io/google-samples/microservices-demo/checkoutservice
imageVersion: v0.8.1
varPort: 5050
envVar:
- name: PORT
  value: "5050"
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
servicePort: 5050
serviceType: ClusterIP