varName: productcatalogservice
replicas:  2
imageName:  gcr.io/google-samples/microservices-demo/productcatalogservice
imageVersion: v0.2.3
varPort:  7000
envVar:
- name: PORT
  value: "7000"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 7000
serviceType: ClusterIP