varName: recommendationservice
replicas:  2
imageName:  gcr.io/google-samples/microservices-demo/recommendationservice
imageVersion: v0.8.1
varPort:  8080
envVar:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 8080
serviceType: ClusterIP