apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.varName }}
spec:
  selector:
    app: {{ .Values.varName }}
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.varPort }}
  type: {{ .Values.serviceType }}
